### CASA0002

# Urban Simulation
***
## Linear Algebra with Numpy

Mateo Neira
***

For both Spatial Interaction Models and Urban Networks it's important to have a basic understanding of linear algebra concepts and to be able to work with and manipulate vectors and matrices in python. 

In this lab we will cover the basics of working with numpy, which will serve as a base for the rest of the practicals in this module.

**Objectives**
* Review basic numpy functions
* define a vector and calculate a vector length and dot product
* define a matrix and calculate a matrix multiplication, transpose, and inverse
* eigenvalues and eigenvectors

## Numpy

Numpy is the fundamental package for scientific computing with Python. It provides numerical functions on _ndarray_ which are fixed size n-dimensional array data structures. Numpy is implemented in C where its memory is more efficiently stored. 

Numpy arrays form the core of nearly the entire ecosystem of data science tools in Python, so time spent learning to use numpy effectively will be useful not only in this module, but other data science applications as well. Here we will be using _ndarray_ to represent vectors and matrices. 

We can import numpy using:

```python
import numpy as np
```



In [1]:
### let's first import the numpy library
import numpy as np

np?

Type:        module
String form: <module 'numpy' from '/opt/conda/lib/python3.10/site-packages/numpy/__init__.py'>
File:        /opt/conda/lib/python3.10/site-packages/numpy/__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use

There are different types of objects (or structures) in linear algebra:
* Scalar: Single number
* Vector: Array of numbers
* Matrix: 2-dimensional array of numbers
* Tensor: N-dimensional array of numbers where n > 2

### Numpy Arrays - Vectors

![1d-array](https://raw.githubusercontent.com/mateoneira/urban_simulation/main/practicals/week1/images/1d.png)

> $x \in \mathbb{R}^n$
 
One dimensional ndarray represent a vector of elements.

For example we can create the following vector $\vec{x} = \begin{bmatrix}2 & 3 & 4 \end{bmatrix}$ in numpy:

```python
x = np.array([2,3,4])
```

In [2]:
### make a 1d array
x=np.array([1,1,1,1,1,1,1,2,2,3,4,5,6,7,8,10])

print (x.ndim)
print (x.size)
print (x.shape)

# similar to python data type (int,float,bool)
print (x.dtype)

1
16
(16,)
int64


### Numpy Arrays - Matrix

![matrix](https://raw.githubusercontent.com/mateoneira/urban_simulation/main/practicals/week1/images/2d.png)

> $X \in \mathbb{R}^{n*m}$

Two dimensional ndarray represents a matrix of elements.

For example we can create the following matrix $ X = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix}$ in numpy:

> X = np.array([[1, 2, 3], [4, 5, 6]])

In [3]:
### make a 2d array
X=np.array([[1,2,3],
            [4,5,6]])

print (X.ndim)
print (X.size)
print (X.shape)
print (X.dtype)

2
6
(2, 3)
int64


### Numpy Arrays - Multidimensional arrays (Tensors)

![tensor](https://raw.githubusercontent.com/mateoneira/urban_simulation/main/practicals/week1/images/3d.png)

We can also use ndarray to create multidimensional arrays. These are often useful to represent tensors.

Images, for example can be represented as a three-dimensional array where the shape = (channel,height, width).

```python
X = np.array([ [[1, 2],[4, 5]],
               [[2, 5], [6, 4]],
               [[2, 5],[6, 4]]])
```

In [5]:
### make a 3d array
# shape(dim, row, col)
X=np.array( [[[1, 2], 
              [4, 5]],
             
             [[2, 5], 
              [6, 4]],
             
             [[2, 5], 
              [6, 4]]])

print (X.ndim)
print (X.size)
print (X.shape)
print (X.dtype)

3
12
(3, 2, 2)
int64


### indexing

Individual elements in arrays can be retrieved using the [] indexer. We can also use the [] indexer to set values of individual array elements. Python is zero-indexed, meaning that the first element has to be accessed with index 0.

```python 
x[0] = 5
```

In [6]:
x=np.array([5,3,8,9])

### indexing
print(x[0])

### setting the value of individual element
### this will set the second element in the vector to 0
x[1]=0
print(x)

5
[5 0 8 9]


In multi-dimensional arrays, items can be accessed using a comma-separated tuple of indices. 

For example the element $x_{1,2}$ from the matrix $X$ can be accessed using:

```python
X[0,1]
```

In [7]:
X = np.array([[1, 2, 3], 
              [4, 5, 6]])
print(X)
print(X[0,1])

X[0,1] = 10
X

[[1 2 3]
 [4 5 6]]
2


array([[ 1, 10,  3],
       [ 4,  5,  6]])

Values can also be modified in multi-dimensional arrays using the same index notation.

In [8]:
X[1,2]=10
X

array([[ 1, 10,  3],
       [ 4,  5, 10]])

### slicing

In the same way that we can use [] to access individual elements, we can also use them to access subarrays with the *slice* notation by using colon (:). 

```python 
x[start:stop:step]
```

By default these values take start = 0, stop = size of dimension, step = 1

In [9]:
### get first two elements
x=np.array([5,0,8,9])
print(x)
x[:2]

[5 0 8 9]


array([5, 0])

In [10]:
### get all elements after second
x[2:]

array([8, 9])

In [11]:
## elements in the middle of the array
x[2:4]

array([8, 9])

In [12]:
## similarly with multi-dimensional arrays
## get first 2 columns and first 2 rows
X = np.array([[ 1, 10,  3], 
              [ 4,  5,  6]])
print(X)
X[:2,:2]

[[ 1 10  3]
 [ 4  5  6]]


array([[ 1, 10],
       [ 4,  5]])

### reshaping

Reshaping is another useful operation, and can be called using the _.reshape_ method. 

As an example, we can create an array of the number 1 through 9, and reshape into a 3 x 3 grid:

```python
x = np.arange(1,10)
X = x.reshape((3,3))
```

In [13]:
# .arange() creates envely spaced values with a given interval
x = np.arange(1,10)
X = x.reshape((3,3))
print(x)
print(X)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### mathematical function

So far we have been discussing some of the basics of numpy, basically creating, accessing and modifying _ndarrays_. However, the power of **numpy** lies in its easy and flexible interface to optimize computation over these _ndarrays_.

### array arithmetic

We can use python native arithmatic operators on _ndarrays_. For example, standard addition, subtraction, multiplication, and division can be used.

In [15]:
# arithmatic operations on arrays 
x = np.array([1, 2, 3])

print (x + 1)
print (x * 2)
print (x ** 2)

a = np.array([1,2])
b = np.array([1,2,3,4])
# a, b should be in the same shape to add
# a+b

[2 3 4]
[2 4 6]
[1 4 9]


Note that these operations are 'broadcasted' to the array. In a nutshell 'broadcasting' describes how numpy treats arrays with different shapes during arithmatic operation. These operations are run element-wise.

see: https://numpy.org/doc/stable/user/basics.broadcasting.html

We can also sum over a given axis in an array using the _.sum()_ method. 

Imagine we have 
$$ T = \begin{bmatrix} 5 & 2 & 10 \\ 6 & 8 & 4 \\ 10 & 4 & 6  \end{bmatrix}$$ 

representing a origin-destination matrix. We can quickly calculate totals at origins $O_i = \sum_j T_{ij}$ and destination $D_j = \sum_i T_{ij}$:

```python
Origins = T.sum(axis=1)
Destinations = T.sum(axis=0)
```

In [18]:
# define array
T = np.array([[5,2,10],
              [6,8,4],
              [10,4,6]
             ])

# sum across rows
origins = T.sum(axis=1)
print(origins)

# sums across columns
destinations = T.sum(axis=0)
print(destinations)

[17 18 20]
[21 14 20]


### dot products

The dot product of two vectors is the sum of the products of elements in the first vector with the corresponding elements in the second vector:

$$ c = a \cdot b $$

```python
c = np.dot(a,b)
```

Dot products are an essential part in matrix multiplication which we will discuss next.

In [19]:
# dot product between two arrays (product-sum between the two arrays)
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
np.dot(v1,v2)

32

### matrix operations

we will end this practical with widely-used operations in linear algebra. Matrix operations for the basis for a lot of the methods we use in urban networks. Although a lot of the computation will be abstracted away once we start using other packages, such as networkx, its important to understand and be able to run these calculations directly with matrices. 

In [20]:
# let's create a square matrix
X = np.random.randint(10, size = (3,3))
X

array([[9, 5, 1],
       [9, 8, 3],
       [2, 9, 6]])

**identity matrix**: the identity matrix contains ones on the main diagnal and zeros in all other positions.

$$ I = \begin{bmatrix} 1 &  0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1  \end{bmatrix}$$

In [22]:
I = np.identity(4, dtype=int)
I

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

The identity matrix has the property that when multiply any matrix of the same dimension, we get back the same matrix.

$$ IX = X $$

### matrix multiplication

matrix multiplication is based on dot products of rows of one matrix with the columns of the other matrix.

```python
np.matmul(A,B)
```

Since the rows of the first matrix are multiplied by the columns of the second matrix, the number of rows of the first matrix must be equal to the number of columns of the second matrix. Please not that because of this, matrix multiplication is **not commutative**: $AB \neq BA$

In [25]:
A = np.random.randint(5, size = (3,3))
B = np.random.randint(5, size = (3,3))

print(A)
print(B)

# 행렬 곱셈
np.matmul(A,B)

#[[2 0 3]          [3 4 0]
# [3 4 4]          [4 0 1]
# [0 0 1]]         [3 0 0]

[[3 0 4]
 [3 2 2]
 [1 1 4]]
[[4 1 2]
 [4 1 1]
 [0 2 0]]


array([[12, 11,  6],
       [20,  9,  8],
       [ 8, 10,  3]])

### eigenvectors and eigenvalues

If we have a square matrix $A$, a non-zero vector $v$ is an eingenvector for A with eigenvalue $\lambda$ if:

$$ A\vec{v} = \lambda \vec{v}$$

We can calculate the eigenvectors and corresponding eigenvalues of a matrix using the linear algebra functions of numpy.

```python
np.linalg.eig(A)
```

In [29]:
print(A)
eigen_vals, eigen_vects = np.linalg.eig(A)
print(eigen_vals)

print('---------------------------------------------------------------')

print(eigen_vects)

[[3 0 4]
 [3 2 2]
 [1 1 4]]
[6.41780209+0.j         1.29109896+1.32703743j 1.29109896-1.32703743j]
---------------------------------------------------------------
[[-0.59067127+0.j         -0.10102062+0.5232819j  -0.10102062-0.5232819j ]
 [-0.62959193+0.j          0.79553003+0.j          0.79553003-0.j        ]
 [-0.50469937+0.j         -0.13044511-0.25707378j -0.13044511+0.25707378j]]


### References

* Python for Data Analysis: Data Wrangling with Pandas, NumPy, and Ipython (Wes McKinney)


* Numpy reference: https://numpy.org/doc/stable/reference/index.html

